# .streamlit/secrets.toml

# Replace "YOUR_ACTUAL_GOOGLE_GEMINI_API_KEY_HERE" with your real Google Gemini API Key.
# IMPORTANT: Do NOT share this file publicly (e.g., on GitHub)!
GOOGLE_API_KEY="AIzaSyA58EK6n0YxB7Em4SVBVMnko4kVDP8SPCw"    